# Generated by Django 5.1.1 on 2024-09-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="tagdescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("image", models.URLField(max_length=1024)),
                ("tags", models.TextField()),
                ("description", models.TextField()),
            ],
        ),
    ]
